### ISSUE TITLE
Bug with 'current' pt B.B - Order of MDT notes and unbale to add 'delivered by' in drugs  

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#606] opened 2015-04-15 14:55 UTC
B.B on current list:

1) OPAT review notes are not in correct chronological order sometimes.  Very odd, when Sarah opend the notes were not in date order.  When i have opened the notes just now, they were not in any kind of date order, but then loged in later and they were in date order. 

2) When i open current IV antibioitcs, there isnt an option to add 'given by'

**Comment by michaeledwardmarks** [comment] 2015-04-15 21:26
What is the patient category set as in the location field?
Should be OPAT.
@davidmiller can I leave you to investigate as VPN from olomon Islands is a bit tricky

**Comment by davidmiller** [comment] 2015-04-16 09:07
Yep, will investigate this as soon as possible - today or tomorrow.

**Comment by davidmiller** [comment] 2015-04-17 08:40
As @michaeledwardmarks guessed, the antibiotics options are a special case of the side-effects of #531 

I have manually re-set the episode to OPAT. This will get fixed with the next release.

WRT the order of the notes - I can't reproduce this at all - they seemed in date order for me.

Can you reproduce the problem reliably @7575colli ?

**Comment by michaeledwardmarks** [comment] 2015-04-26 06:38
I'm closing this as it seems we have fixed the issue.
Re-open if not true.

**Closed by michaeledwardmarks** 2015-04-26 06:38 UTC
Labels: bug, elCID Live
