### ISSUE TITLE
Autocomplete on text fields

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/elcid#890] opened 2015-12-11 10:24 UTC
it should be autocomplete off (as is put in the template tag) some where along for forms such as Diagnosis in the discharge panel this is changing to autocomplete="false (in the rendered html). Fix this please.

**Comment by davidmiller** [comment] 2016-07-29 07:50
Closing as a duplicate of #1253

**Closed by davidmiller** 2016-07-29 07:50 UTC
