### ISSUE TITLE
What is the default view when choose patient on search?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#960] opened 2016-02-12 11:59 UTC
Seems to default to inpatient. If I were Vanya, I'd want it to default to haem view (like it does on 0.5 when clicked on haematology consult). I haven't spotted any rules here. Missed something?

**Comment by davidmiller** [comment] 2016-03-18 16:05
I think this is  a duplicate of #941 - going to close this ....

**Closed** 2016-03-18 16:05 UTC
Labels: Design, discussion
