### ISSUE TITLE
Assignment instead of equality test in ng-show logic will always return Truthy

### ISSUE THREAD

**Issue by pacharanero** [openhealthcare/elcid#1572] opened 2018-03-26 12:42 UTC
In elcid-uch /elcid/templates/wardrounds/discharged_detail.html we have:

https://github.com/openhealthcare/elcid/blob/d33f828efc14aae2a58534ce886250666c58cd86/elcid/templates/wardrounds/discharged_detail.html#L30

We found this while implementing a fix to https://github.com/openhealthcare/elcid/issues/1557 -  @fredkingham and I were looking into what `hide_discharge_action` does and found that a) the flag `hide_discharge_action` doesn't appear to be set _anywhere_ in the Opal or Elcid codebases, and b) this expression will _assign_ `hide_discharge_action=true`, which always returns `true` and therefore the `ng-show` span is always shown, irrespective of the state of `hide_discharge_action`.

fix: 
* [ ] `<span ng-show="hide_discharge_action===true">`
* [ ] consider whether `hide_discharge_action` should be *set* somewhere else in the code?

**Comment by davidmiller** [comment] 2018-11-01 14:05
This is the intended behaviour - e.g. it's _supposed_ to assign there....
We've removed the flag wholesale as of Opal 0.13.0 - closing this accordingly.

**Closed as completed by davidmiller** 2018-11-01 14:06 UTC
Labels: bug
