### ISSUE TITLE
Confirm Final Diagnosis Button Incorrectly showing up on OPAT Review Ward Round

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#1091] opened 2016-05-13 13:18 UTC
With weird behaviours also.
Options 
1) No button at all
2) Button to open the Final OPAT Outcome Modal

**Comment by fredkingham** [comment] 2016-05-19 09:53
our wardround query looks at whether there is an opat outcome. The wardround action logic looks at the category of the episode.

As create random data will just create subrecords and categories willy nilly, we can end up instances like this that should be impossible in the wild. As such I'm closing this as essentially a dupe of openhealthcare/opal#504 (but I'll reference it as its something that needs to be fixed by that ticket)

**Closed by fredkingham** 2016-05-19 09:53 UTC
Labels: bug, in progress
