### ISSUE TITLE
On advice view, the field "discussed with" needs to be the same as what was saved on the previous patient by default

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#730] opened 2015-09-11 13:21 UTC

**Comment by davidmiller** [comment] 2015-09-14 09:06
Duplicate of #721 (closing)

**Comment by GabPoll** [comment] 2015-09-14 09:47
this one not covered by #721, i don't think.

**Comment by davidmiller** [comment] 2015-09-14 10:27
It is now !

**Closed by davidmiller** 2015-09-14 10:27 UTC
