### ISSUE TITLE
As a user I would like fields with n entries from a lookuplist to be split into n records

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/elcid#330] opened 2014-07-22 21:05 UTC
e.g if in PMH user enters:
Rheumatoid arthritis, Type 2 Diabetes, Lung Cancer

system should save these as:
Rheumatoid Arthritis
Type 2 Diabetes
Lung Cancer

**Comment by davidmiller** [comment] 2015-01-29 15:24
I think this is a duplicate of #312 no ?

**Comment by michaeledwardmarks** [comment] 2015-01-29 15:42
No.
#312 is that the user should be able to to type fever, cough, shortness of breath
and that after each comma the user should be offered the lookup list
(Auto-completion of many single line entries - functionality used to exist)

This ticket is that
each of those should be saved as a separate entry

**Comment by davidmiller** [comment] 2015-01-29 16:11
Sorry - that's actually explained in that ticket. 
Apologies.

**Comment by davidmiller** [comment] 2015-01-29 16:15
OK. Coming back to this, I'm less than convinced that this is a good idea :) 

It's a surprising hidden behaviour, and I'm not currently sure that it's actually the right thing to do in all cases.

Presumably the assertion is that the time saved by the functionality is > the time spent training every user that this is how it works & overcoming their surprise :)

**Comment by michaeledwardmarks** [comment] 2015-01-29 17:06
Happy to put this on hold.

**Closed** 2015-02-15 09:32 UTC
Labels: enhancement, Future
