### ISSUE TITLE
Do we want a "Review symptoms" button in patient bar on list view?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#697] opened 2015-08-27 09:40 UTC
Thoughts specifically for @michaeledwardmarks on this one.

If no presenting symptoms entered, there is a useful "+ symptoms" button. However, once entered, editing that field requires user knowing it's inside Patient details.

Thoughts on a "Review symptoms" button? Or is it deliberately hidden so that first impression is documented and then hidden to avoid editing.

**Comment by michaeledwardmarks** [comment] 2015-08-31 03:12
@davidmiller @GabPoll I think the issue is there is a regression on the Heroku version.
Previously (and currently on elcid-live) the symptoms once saved were displayed as a 'sub-compartment' of the diagnosis/issues column.
This is no longer the case and hence why it is difficult to edit them - need to make sure we fix this before pushing the next deployment

**Comment by davidmiller** [comment] 2015-08-31 07:48
I haven't logged in to check, but I'd strongly suspect that this has been the case since 0.4.0 - e.g. on ELCIDL@UCH.

**Comment by GabPoll** [comment] 2015-08-31 08:04
this has been the case since 0.4.0, agree. It's since symptoms was moved from the list to the patient details box.

**Comment by michaeledwardmarks** [comment] 2016-02-05 10:56
I think this is now fixed - we collect at discharge and the +symptoms button has returned in 0.5.2/3 and 0.6

**Closed by michaeledwardmarks** 2016-02-05 10:56 UTC
Labels: bug, discussion, elCID Live
