### ISSUE TITLE
Can we import clinical information from an OPAT episode to a new inpatient episode

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/elcid#1547] opened 2018-03-01 13:20 UTC
OPAT patient admitted. Created new inpatient episode on Tropical inpatients, but had to re-enter all the diagnoses, PMHx, etc...

At present when an inpatient goes onto OPAT referral list, this info is imported into the new episode. Can we do something similar the other way round?

**Comment by davidmiller** [comment] 2018-03-23 14:43
Closing as a duplicate of #1550

**Closed as completed by davidmiller** 2018-03-23 14:43 UTC
Labels: enhancement
