### ISSUE TITLE
Antimicrobial fields - lots of data difficult to digest when pt has same antibiotic given by multiple people 

### ISSUE THREAD

**Issue by 7575colli** [openhealthcare/elcid#595] opened 2015-02-24 20:37 UTC
Pts who are having the same antibiotic given by lots of different teams (i.e inpatient/DN/clinic), there ends up being loads of entries that are messy to look though.

See example bellow.  I realise that the more current version notes the number of days next to the date which is super helpful and a real life saver.  But looking though this, it is difficult to note if there were any gaps in the Teicoplanin - at a glance it appress that it stopped and then restarted   

 18/01-09/02 Teicoplanin 500mg IV OD Inpatient Team 
 12/01-18/01 Teicoplanin 500mg IV OD District Nurse 
 08/01-11/01 Teicoplanin 500mg IV OD UCLH@Home 
 07/01-11/01 Ceftriaxone 2g IV OD UCLH@Home 
 05/01-09/01 Amoxicilin 1g PO QDS 
 04/01-07/01 Teicoplanin 500mg IV OD OPAT Clinic 
 01/01-03/01 Teicoplanin 500mg IV OD Inpatient Team 

Maybe a solution could be that a drug with no interruption in date or dose has the 'delivered by' noted bellow.  i.e:

Meropenem 2g IV TDS D 17 (start 01/01 - stop 17/01) 
01/01 - 03/01 D3 - Inpateint
04/01 - 09/01 D6 - Clinic
10/01 - 14/01 D5 - UCLH@home
15/01 - 17/01 D3 - District Nurse

Note that next antibiotic tittle above, i have added a cumulative number of days that Meropenem was given and a start / stop date to summarise the detail.  
 
Amoxacillin 500mg PO OD
01 - 06 D7 Inpatient 

Etc etc

This is visually much easier to digest. If a dose change or gap in dates, then a new antibiotic title is created.  

All thoughts, suggestions welcomed.  Although i appreciate that my suggestion my be unrealistic given the resources available - happy to be rained in if need be!

**Comment by michaeledwardmarks** [comment] 2015-02-24 20:42
I'm closing this as a duplicate of #421

**Closed by michaeledwardmarks** 2015-02-24 20:42 UTC
Labels: elCID OPAT
